[project]
name = "custom-server"
version = "0.1.0"
description = "Example custom MCP server on Databricks Apps"
readme = "README.md"
authors = [
    { name = "renardeinside", email = "polarpersonal@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.12",
    "mcp[cli]<2",
    "uvicorn>=0.34.2",
    "databricks-sdk"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
custom-server = "custom_server.main:main"